  wheel_right_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: wheel_right_joint
    pid: {p: -0.01, i: 0.8, d: 0.0}
  wheel_left_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: wheel_left_joint
    pid: {p: -0.01, i: 0.8, d: 0.0}

  
